vagrantfile:
    target: local
    vm:
        provider:
            local:
                chosen_virtualizer: parallels
        synced_folder:
            vflsf_e9d1fetqzntj:
                sync_type: nfs